config/routes.rb
Rails.application.routes.draw do

  namespace :api do
  get 'events/create'
  end

  devise_for :users

  resources :registered_applications

  root 'welcome#index'

  namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :registered_application
end

app/models/registered_application.rb
class RegisteredApplication < ActiveRecord::Base
  belongs_to :user

  has_many :events

  validates :url, :url => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :registered_applications, dependent: :destroy
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  skip_before_action :authenticate_user!
  skip_before_action :verify_authenticity_token

  before_filter :set_access_control_headers

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end

  def create
    registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])

    if registered_application.nil?
      return render json: "Unregistered application", status: :unprocessable_entity
    elsif @event = registered_application.events.create(event_params)
      render json: @event, status: :created
    else
      render json: {errors: @event.errors}, status: :unprocessable_entity
    end
  end

  def preflight
    head 200
  end

  private

  def event_params
    params.require(:event).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  before_action :set_registered_application, only: [:show, :edit, :update, :destroy]

  # GET /registered_applications
  def index
    @registered_applications = RegisteredApplication.all
  end

  # GET /registered_applications/1
  def show
    @registered_application = RegisteredApplication.find(params[:id])
    @events = @registered_application.events.group_by(&:name)
  end

  # GET /registered_applications/new
  def new
    @registered_application = RegisteredApplication.new
  end

  # GET /registered_applications/1/edit
  def edit
  end

  # POST /registered_applications
  def create
    @registered_application = RegisteredApplication.new(registered_application_params)

    if @registered_application.save
      redirect_to @registered_application, notice: 'Registered application was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /registered_applications/1
  def update
    if @registered_application.update(registered_application_params)
      redirect_to @registered_application, notice: 'Registered application was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /registered_applications/1
  def destroy
    @registered_application.destroy
    redirect_to registered_applications_url, notice: 'Registered application was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registered_application
      @registered_application = RegisteredApplication.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def registered_application_params
      params.require(:registered_application).permit(:name, :url)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/api/events_helper.rb
module API::EventsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BadaBingo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
       <% if user_signed_in? %>
         Signed in as: <strong><%= current_user.email %></strong> |
         <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
       <% else %>
         <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
         <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
       <% end %>
    </div>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/registered_applications/_form.html.erb
<%= form_for(@registered_application) do |f| %>
  <% if @registered_application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@registered_application.errors.count, "error") %> prohibited this registered_application from being saved:</h2>

      <ul>
      <% @registered_application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control', placeholder: "Enter application title" %>

  <%= f.label :url %>
  <%= f.text_field :url, rows: 8, class: 'form-control', placeholder: "Enter application url" %>

  <%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/registered_applications/edit.html.erb
<h1>Editing Registered Application</h1>

<%= render 'form' %>

<%= link_to 'Show', @registered_application %> |
<%= link_to 'Back', registered_applications_path %>

app/views/registered_applications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Registered Applications</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @registered_applications.each do |registered_application| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to registered_application.name, registered_application %>
          </h4>
          <p><%= link_to 'Edit', edit_registered_application_path(registered_application) %></p>
          <p><%= link_to 'Delete', registered_application, method: :delete, data: { confirm: 'Are you sure?' } %></p>
          <small>
            <%= registered_application.url %>
          </small>
        </div>
        <hr>
      </div>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Registered application', new_registered_application_path %>

app/views/registered_applications/new.html.erb
<h1>Register a New Application</h1>

<%= render 'form' %>

<%= link_to 'Back', registered_applications_path %>

app/views/registered_applications/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Home', root_path %> |
<%= link_to 'Edit this Application', edit_registered_application_path(@registered_application) %> |
<%= link_to 'My Registered Applications', registered_applications_path %>

<h1><%= @registered_application.name %></h1>

<div class="row">
  <div class="col-md-8">
    <h3><%= @registered_application.url %></h3>
    <% @events.each do |event_name, events| %>
      <p> <%= event_name %> : <%= events.size %>
        <%= events.size > 1 ? "events" : "event" %> </p>
    <% end %>
    <%= pie_chart @registered_application.events.group(:name).count %>
    <%= line_chart @registered_application.events.group_by_day(:created_at).count %>
  </div>
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<%= link_to 'My Registered Applications', registered_applications_path %>